### ISSUE TITLE
ClangSharpPInvokeGenerator fails on ARM64 host with dotnet arm64 sdk+runtime

### ISSUE THREAD

**Issue by riverar** [dotnet/ClangSharp#404]
Originally from https://github.com/microsoft/win32metadata/issues/1305.

```
Package Id                      Version      Commands
-----------------------------------------------------------------------
clangsharppinvokegenerator      15.0.1       ClangSharpPInvokeGenerator

dotnet --version
7.0.100-rc.2.22477.23
```
(Tried with other dotnet SDKs to no avail.)

1. Install dotnet **arm64** sdk/runtime
2. `dotnet tool update -g ClangSharpPInvokeGenerator`
3. `"" > test.input`
4. `ClangSharpPInvokeGenerator -f test.input -n test -o test.output`
5. Observe exception

```
Unhandled exception: System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (0x8007000B)
   at ClangSharp.Interop.clang.getClangVersion()
   at ClangSharp.PInvokeGenerator..ctor(PInvokeGeneratorConfiguration config, Func`2 outputStreamFactory) in /_/sources/ClangSharp.PInvokeGenerator/PInvokeGenerator.cs:line 75
   at ClangSharp.Program.Run(InvocationContext context) in /_/sources/ClangSharpPInvokeGenerator/Program.cs:line 686
   at System.CommandLine.Handler.<>c__DisplayClass1_0`1.<SetHandler>b__0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.<>c__DisplayClass2_0.<.ctor>g__Handle|0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass20_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass9_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

Appears the root cause here is the amd64 libclang in the package getting chosen to load into the AnyCPU (arm64) process.

**Comment by tannergooding** [comment]
https://github.com/dotnet/ClangSharp/pull/408 should minimally help by logging an error message directing users to acquire the relevant binaries from NuGet. In particular https://www.nuget.org/packages/libclang and https://www.nuget.org/packages/libClangSharp and the `.runtime.<rid>` specific versions such as https://www.nuget.org/packages/libClangSharp.runtime.win-arm64

I've logged https://github.com/dotnet/sdk/issues/28923 on the dotnet/SDK side to ensure this issue is more broadly tracked and an applicable fix can be made to the dotnet tool support.

**Comment by tannergooding** [comment]
See also https://github.com/microsoft/win32metadata/issues/1305#issuecomment-1295303952

**Comment by riverar** [comment]
Agreed, will close this as I don't need it and we're blocked on dotnet. https://github.com/microsoft/win32metadata/issues/1305#issuecomment-1570974007
