### ISSUE TITLE
It happens ""Only <include-path-to-header> can be included directly.""

### ISSUE THREAD

**Issue by DeafMan1983** [dotnet/ClangSharp#502]
I have got many `"Only <glib-object.h> can be included directly."`
I already tried. But ClangSharpPInvokeGenerator prases and throws errors and I have tried some configurations.... like in Xlib's generator files and I have to 10 or more times. No success...

But my output is very larger 
```
ClangSharpPInvokeGenerator @gobject.rsp
Diagnostics for '/Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h':
    /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h:23:2: error: "Only <glib-object.h> can be included directly."
    /Applications/Gtk4.12.4/include/glib-2.0/gobject/gtype.h:23:2: error: "Only <glib-object.h> can be included directly."
    /Applications/Gtk4.12.4/include/glib-2.0/gobject/gvalue.h:25:2: error: "Only <glib-object.h> can be included directly."
    /Applications/Gtk4.12.4/include/glib-2.0/gobject/gparam.h:25:2: error: "Only <glib-object.h> can be included directly."
    /Applications/Gtk4.12.4/include/glib-2.0/gobject/gclosure.h:24:2: error: "Only <glib-object.h> can be included directly."
    /Applications/Gtk4.12.4/include/glib-2.0/gobject/gsignal.h:23:2: error: "Only <glib-object.h> can be included directly."
    /Applications/Gtk4.12.4/include/glib-2.0/gobject/gboxed.h:23:2: error: "Only <glib-object.h> can be included directly."
    /Applications/Gtk4.12.4/include/glib-2.0/gobject/glib-types.h:23:2: error: "Only <glib-object.h> can be included directly."
Skipping '/Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h' due to one or more errors listed above.

Processing '/Applications/Gtk4.12.4/include/glib-2.0/glib-object.h'
Diagnostics for binding generation of /Applications/Gtk4.12.4/include/glib-2.0/glib-object.h:
    Warning (Line 44, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'G_TYPE_IS_OBJECT'. Generated bindings may be incomplete.
    Warning (Line 54, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'G_OBJECT'. Generated bindings may be incomplete.
    Warning (Line 61, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'G_OBJECT_CLASS'. Generated bindings may be incomplete.
    Warning (Line 69, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'G_IS_OBJECT'. Generated bindings may be incomplete.
    Warning (Line 80, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'G_IS_OBJECT_CLASS'. Generated bindings may be incomplete.
    Warning (Line 89, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'G_OBJECT_GET_CLASS'. Generated bindings may be incomplete.
    Warning (Line 98, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'G_OBJECT_TYPE'. Generated bindings may be incomplete.
    Warning (Line 108, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'G_OBJECT_TYPE_NAME'. Generated bindings may be incomplete.
    Warning (Line 117, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'G_OBJECT_CLASS_TYPE'. Generated bindings may be incomplete.
    Warning (Line 127, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'G_OBJECT_CLASS_NAME'. Generated bindings may be incomplete.
    Warning (Line 136, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'G_VALUE_HOLDS_OBJECT'. Generated bindings may be incomplete.
    Warning (Line 155, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'G_INITIALLY_UNOWNED'. Generated bindings may be incomplete.
    Warning (Line 163, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'G_INITIALLY_UNOWNED_CLASS'. Generated bindings may be incomplete.
    Warning (Line 170, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'G_IS_INITIALLY_UNOWNED'. Generated bindings may be incomplete.
    Warning (Line 178, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'G_IS_INITIALLY_UNOWNED_CLASS'. Generated bindings may be incomplete.
    Warning (Line 187, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'G_INITIALLY_UNOWNED_GET_CLASS'. Generated bindings may be incomplete.
    Warning (Line 548, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'g_object_ref'. Generated bindings may be incomplete.
    Warning (Line 549, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'g_object_ref_sink'. Generated bindings may be incomplete.
    Warning (Line 683, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'G_OBJECT_WARN_INVALID_PSPEC'. Generated bindings may be incomplete.
    Warning (Line 705, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'G_OBJECT_WARN_INVALID_PROPERTY_ID'. Generated bindings may be incomplete.
    Warning (Line 710, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'g_clear_object'. Generated bindings may be incomplete.
    Warning (Line 777, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'g_set_object'. Generated bindings may be incomplete.
    Warning (Line 828, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'g_assert_finalize_object'. Generated bindings may be incomplete.
    Warning (Line 861, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'g_clear_weak_pointer'. Generated bindings may be incomplete.
    Warning (Line 929, Column 9 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Function like macro definition records are not supported: 'g_set_weak_pointer'. Generated bindings may be incomplete.
    Warning (Line 445, Column 13 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Unsupported attribute: 'Const'. Generated bindings may be incomplete.
    Warning (Line 470, Column 10 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Unsupported attribute: 'Sentinel'. Generated bindings may be incomplete.
    Warning (Line 474, Column 13 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Unsupported attribute: 'Sentinel'. Generated bindings may be incomplete.
    Warning (Line 478, Column 13 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Unsupported attribute: 'Sentinel'. Generated bindings may be incomplete.
    Warning (Line 482, Column 10 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Unsupported attribute: 'Sentinel'. Generated bindings may be incomplete.
    Warning (Line 763, Column 21 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Unsupported statement class: 'GNUNullExpr'. Generated bindings may not be unchecked.
    Warning (Line 768, Column 21 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Unsupported statement class: 'GNUNullExpr'. Generated bindings may not be unchecked.
    Warning (Line 819, Column 3 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Unsupported statement class: 'PredefinedExpr'. Generated bindings may not be unchecked.
    Error (Line 819, Column 3 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Unsupported statement: 'PredefinedExpr' in g_assert_finalize_object(GObject *):void. Generated bindings may be incomplete.
    Warning (Line 822, Column 3 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Unsupported statement class: 'PredefinedExpr'. Generated bindings may not be unchecked.
    Error (Line 822, Column 3 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Unsupported statement: 'PredefinedExpr' in g_assert_finalize_object(GObject *):void. Generated bindings may be incomplete.
    Warning (Line 854, Column 17 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Unsupported statement class: 'GNUNullExpr'. Generated bindings may not be unchecked.
    Warning (Line 857, Column 32 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Unsupported statement class: 'GNUNullExpr'. Generated bindings may not be unchecked.
    Warning (Line 918, Column 21 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Unsupported statement class: 'GNUNullExpr'. Generated bindings may not be unchecked.
    Warning (Line 923, Column 21 in /Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h): Unsupported statement class: 'GNUNullExpr'. Generated bindings may not be unchecked.
Unhandled exception: System.IO.IOException: The file '/Applications/DeafMan1983.Interop.GLib/GobjectInterop.cs' already exists.
   at System.IO.FileSystem.CreateDirectory(String fullPath, UnixFileMode unixCreateMode)
   at System.IO.Directory.CreateDirectory(String path)
   at ClangSharp.PInvokeGenerator.<>c.<.ctor>b__44_0(String path) in /_/sources/ClangSharp.PInvokeGenerator/PInvokeGenerator.cs:line 133
   at ClangSharp.PInvokeGenerator.Close() in /_/sources/ClangSharp.PInvokeGenerator/PInvokeGenerator.cs:line 388
   at ClangSharp.PInvokeGenerator.Dispose(Boolean isDisposing) in /_/sources/ClangSharp.PInvokeGenerator/PInvokeGenerator.cs:line 2227
   at ClangSharp.PInvokeGenerator.Dispose() in /_/sources/ClangSharp.PInvokeGenerator/PInvokeGenerator.cs:line 1569
   at ClangSharp.Program.Run(InvocationContext context) in /_/sources/ClangSharpPInvokeGenerator/Program.cs:line 800
   at System.CommandLine.Handler.<>c__DisplayClass1_0`1.<SetHandler>b__0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.<>c__DisplayClass2_0.<.ctor>g__Handle|0(InvocationContext context)
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass18_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass13_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass20_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__19_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass9_0.<<UseExceptionHandler>b__0>d.MoveNext()
```
But ClangSharpPInokeGenerator cannot generate from `glib-object.h` to cs file like I saw empty cs file.

It is qobject.rsp:
```
-f
/Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h
/Applications/Gtk4.12.4/include/glib-2.0/glib-object.h
--traverse
/Applications/Gtk4.12.4/include/glib-2.0/gobject/gobject.h
--namespace
DeafMan1983.Interop.Gobject
--methodClassName
Gobject
-o
./GobjectInterop.cs
--include-directory
/Applications/Gtk4.12.4/include/glib-2.0
/usr/lib/gcc/x86_64-linux-gnu/11/include
/usr/include/x86_64-linux-gnu
/Applications/Gtk4.12.4/lib/x86_64-linux-gnu/glib-2.0/include
--config
generate-macro-bindings
multi-file
preview-codegen
trimmable-vtbls
multi-file
--additional
-m64
-Wno-deprecated-declarations
-Wno-expansion-to-defined
-Wno-extern-c-compat
-Wno-extern-initializer
-Wno-extra-tokens
-Wno-ignored-attributes
-Wno-ignored-pragma-intrinsic
-Wno-macro-redefined
-Wno-nonportable-include-path
-Wno-pragma-pack
--with-librarypath
*=libgobject-2.0
```
Because I really need to prepare for GTK3/4 into dotnet 8.

I know that Gtk3Sharp doesn't support for Dotnet8's nativeaout.
That is why I have made some GTk4 into dotnet but it is not completely.
My Gtk4 Wrapper is still in development.
![image](https://github.com/dotnet/ClangSharp/assets/57066679/76cdc9b7-5927-4b4d-9bbc-6cf7912a02e6)
That is beautifully.

I hope you understand me. How do I fix with `"Only <glib-object.h> can be included directly."`

Thanks and sorry for my bad English!

//EDIT:
How do I remove/skip deprecated functions?

If I expected which many deprecated functions like `g_async_queue_timed_pop()`
Because sometimes functions show warning "Glib:Warning deprecated function <function-name>"

Thanks!

**Comment by DeafMan1983** [comment]
For `g_print()` and other print-like functions cannot use it.

How do I use an alternative to `params object[]` if I passed `g_print(const char* fmt, ...)` to in C# But ClangSharpPInvokeGenerator tells wrong? Is it correct or wrong with `__arglist()`

How do I fix it?

**Comment by tannergooding** [comment]
`varargs` have never been "properly" supported in .NET, its not something you can readily consume.

For Windows only you can somewhat make it work via the undocumented `__arglist` and `System.ArgIterator`, but they do not always work as expected.

**Comment by DeafMan1983** [comment]
Oh only Windows? I thought `Console.WriteLine()` can work on Linux. It is really impossibly. But I use manual with `string.Format()` for `g_printf()` without `params object[]` or `__arglist`
👍

**Comment by tannergooding** [comment]
`Console.WriteLine` works everywhere as it uses `params object[]`

`varargs`, which is what `printf` uses, is only available on Windows and which would be required for interop.

They are different approaches to the same general problem
